{% set version = "1.42.0" %}

package:
  name: libuv
  version: {{ version }}

source:
  fn: libuv-v{{ version }}.tar.gz
  url: https://github.com/libuv/libuv/archive/v{{ version }}.tar.gz
  sha256: 371e5419708f6aaeb8656671f89400b92a9bba6443369af1bb70bcd6e4b3c764
  patches:
    # the tty test fails because of the build machine setup, skip it
    - disable_tty_test.patch  # [ppc64le]
    - 0001-Skip-the-single-bit-that-fails-in-test-fs-copyfile-w.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libuv') }}

requirements:
  build:
    - {{ compiler('c') }}
    - automake             # [unix]
    - autoconf             # [unix]
    - libtool              # [unix]
    - make                 # [unix]

test:
  commands:
    - test -f "%PREFIX%/Library/include/uv.h"  # [win]
    - test -f "$PREFIX/include/uv.h"  # [unix]
    - test -f "$PREFIX/lib/libuv.a"  # [unix]
    - test -f "$PREFIX/lib/libuv.so.1"  # [linux]
    - test -f "$PREFIX/lib/libuv.1.dylib"  # [osx]
    - test -f "$PREFIX/lib/libuv${SHLIB_EXT}"  # [not win]

about:
  home: http://libuv.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Cross-platform asynchronous I/O'
  description: |
    libuv is a multi-platform support library with a focus on asynchronous I/O.
    It was primarily developed for use by Node.js, but it's also used by Luvit,
    Julia, pyuv, and others.
  doc_url: http://docs.libuv.org/
  doc_source_url: https://github.com/libuv/libuv/tree/v1.x/docs
  dev_url: https://github.com/libuv/libuv

extra:
  recipe-maintainers:
    - frol
    - mariusvniekerk
