# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "QjR91vpeo5HmfS5QB6bQpbRme16gIqL/epwqS8FUqczC+Ry09ebFk5ECw2R2METeXzjiIFQfXZ0sAKjRSUeIjnL0yamtOIuyGTc89G1sXvAFIZGT6ZCXeLRQzKR4+AH3S0U/FWVdatkDWocVmPSSkeVwcJfb/A3rqAbQCUKnVENglQHtyoGo08L4uCaalfvasjwYn/pMzcpNRnRX9PiwaHbTqGpIefSpKKjMMYI1E9hnV16UVOMbJbzMX6J3rLf5BhFAS7An95X8pfXvzP5g7cZ80pWxNwFx6kFYaq6VrHFcYT3KrznKgiX6Kzk72P938BNrtGzvxtuRF5eXrcM8egX9E5IVLJeuuEuNYaim+LfQf2/L3v+IUgOjcS0oV7OgcnYfC1ir8tj0sz8NjkbO92rxuclqDm4/nbKIqGHhLY/4cIZFTvJegGYmXDEIUM44OgtsUce7PO+xOFSIV48BkDnmFD6fB7X5DpwCbs5N77d76frgqoq2A2LnNp7qDpEtYuTNchmLAaAetdM3khcJrM1qQhV6dbUqJnPR0yo65WFaqo3beQcXjUszxBp9MIUUKiAbF7USW6kd/130esKJkEyTrulpWbBXxpYz/ZGqC/rtI5eYC1IP2B+9AEqJubZkR/7AFGLT5RAPNTdy39Id+rntdsmtubzLvh/DVHkieK0="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
