travis:
  secure:
    BINSTAR_TOKEN: HLszl/6wwqrFJ1gPyT4DpM805lp8uddOdQfk9nlkRMl3VRVsZKAr75s2y2Ol90XAjsocFfVDKS1+faZSB43BUT52kdFGdPK46NrOUX+wvgMngfnGCZaQacBZ9KsRqLeYiHomKz3USL+T9ZODr1SmRq1lj27lGJFJe9sLW3zcFeZtZ75gUbiBvwUyt+Mr52opCgj7ORSSo/1tS1xHzyUP/i0sQrfLMCeFnV1SnPMd9q1l5AhcSh0vc6A6+w1LGaIEmPkK18cD4aWT+e4r5zI0+fLvv2nksN5F2kOhkJz9Jc0RnY6HPd6ITjOVkaTSYK/ThNjQ+LL/jMSNZ7H9hV5p+wsXHNxG3tYVd6uFUFiZ5nDTHHT9QDPaSpHUITAEbSX4ErY1NAYeZ9P+SmI8JXcyFty85cbrNicDXy0odaNf81ZcJq+Ch9SWB3iwb8/dXjxccXxu/ZrbUlXLPPnKGvHZghyJPovgyZdqklS860n5/+Qw4L/fMuoG7+Sn4d8EpG7gsDdhXWcPilxy0QWKvnY3vobQYAq+a4V2WK1h2INYSrCcBSJ7RNhGwADzEKz03RpHCynzUueo2+OF7AgMAXq6vXf0f1yc2XIry3/YdHWC0ojOCmLZH83JlrmWNCjS4+UvoDAH4MaZ9DzHvgjFwhZgjR38hMENRO9dje0lSZxu1N8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
