travis:
  secure:
    BINSTAR_TOKEN: QjR91vpeo5HmfS5QB6bQpbRme16gIqL/epwqS8FUqczC+Ry09ebFk5ECw2R2METeXzjiIFQfXZ0sAKjRSUeIjnL0yamtOIuyGTc89G1sXvAFIZGT6ZCXeLRQzKR4+AH3S0U/FWVdatkDWocVmPSSkeVwcJfb/A3rqAbQCUKnVENglQHtyoGo08L4uCaalfvasjwYn/pMzcpNRnRX9PiwaHbTqGpIefSpKKjMMYI1E9hnV16UVOMbJbzMX6J3rLf5BhFAS7An95X8pfXvzP5g7cZ80pWxNwFx6kFYaq6VrHFcYT3KrznKgiX6Kzk72P938BNrtGzvxtuRF5eXrcM8egX9E5IVLJeuuEuNYaim+LfQf2/L3v+IUgOjcS0oV7OgcnYfC1ir8tj0sz8NjkbO92rxuclqDm4/nbKIqGHhLY/4cIZFTvJegGYmXDEIUM44OgtsUce7PO+xOFSIV48BkDnmFD6fB7X5DpwCbs5N77d76frgqoq2A2LnNp7qDpEtYuTNchmLAaAetdM3khcJrM1qQhV6dbUqJnPR0yo65WFaqo3beQcXjUszxBp9MIUUKiAbF7USW6kd/130esKJkEyTrulpWbBXxpYz/ZGqC/rtI5eYC1IP2B+9AEqJubZkR/7AFGLT5RAPNTdy39Id+rntdsmtubzLvh/DVHkieK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
